version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:16  # يمكنك تعديل رقم الإصدار حسب الحاجة
    steps:
      - checkout  # لعمل check-out للكود من مستودع Git
      - run:
          name: Install dependencies
          command: npm install  # لتثبيت الحزم عبر npm
      - run:
          name: Start application
          command: npm start  # لتشغيل التطبيق

  deploy:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Deploy to production server
          command: ./deploy_script.sh  # استبدل هذا بالسكربت المناسب للنشر

workflows:
  version: 2
  deploy_workflow:
    jobs:
      - build
      - deploy:
          requires:
            - build